name: Clone All Org Repos

on:
  workflow_dispatch: #

jobs:
  clone-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install git-secrets
        run: |
          sudo apt-get update && sudo apt-get install -y git-secrets
          git secrets --register-aws
          git secrets
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate with GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: gh auth login --with-token <<< "$GH_TOKEN"

      - name: Fetch and Clone All Repositories
        env:
          ORG_NAME: Organizationgitrsecrets1
        run: |
          mkdir -p org-repos
          cd org-repos
          
          # List all repositories and clone them
          gh repo list $ORG_NAME --limit 100 --json nameWithOwner --jq '.[].nameWithOwner' | while read repo; do
            gh repo clone "$repo"
          done

      - name: Run Scan
        run: |
          pwd
          
          
      

